---
title: "CD45+Thy1+ ILC GSE map analysis"
output:
   html_document: 
     theme: united
     df_print: kable
     toc: yes
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
---

```{r setup, include = FALSE}
all_times <- list()  # store the time for each chunk
knitr::knit_hooks$set(time_it = local({
  now <- NULL
  function(before, options) {
    if (before) {
      now <<- Sys.time()
    } else {
      res <- difftime(Sys.time(), now, units = "secs")
      all_times[[options$label]] <<- res
    }
  }
}))
knitr::opts_chunk$set(
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 95),
  message = FALSE,
  warning = FALSE,
  time_it = TRUE
)
```


# Universal packages

```{r Load packages}
library(Seurat)
library(tidyverse)
library(patchwork)
library(cowplot)
```


# Data input

```{r Load SCT processed ILC data}
# Load ILC data

# ILC
ILC <- readRDS("CD45_Thy1_ILC_paper_ver.rds")


# Set RNA assay as default
DefaultAssay(ILC) <- "RNA"
head(x = ILC[[]])
```


# ILC cluster Visualization

```{r Set Reveal ILC clusters}
# Show the numbers for ILC
table(ILC@meta.data$cell_type, split.by = ILC@meta.data$treatment)

# Plot the ILC clusters
DimPlot(ILC, group.by = "cell_type", label = T, repel =  T)
DimPlot(ILC, group.by = "cell_type", split.by = "treatment", label = F) + ggtitle(NULL)
```


# ILC subsets

```{r ILC subsets}
# NK/ILC1
NK_ILC1 <- ILC %>%
    subset(idents = c("NCR1 NK/ILC1", "IFNg NK/ILC1", "ST2 NK/ILC1"), invert = FALSE) %>%
    SetIdent(value = "treatment")

table(NK_ILC1@meta.data$cell_type, split.by = NK_ILC1@meta.data$treatment)

# ILC2
ILC2 <- ILC %>%
    subset(idents = c("Areg ILC2", "IL-13 ILC2", "IL-10 ILC2", "Quiescent ILC2", "KLRG1 ILC2", "LTB ILC2"), invert = FALSE) %>%
    SetIdent(value = "treatment")

table(ILC2@meta.data$cell_type, split.by = ILC2@meta.data$treatment)
```


# Packages for differential expression with volcano plot and enrichment network

```{r Load the packages for enrichment network}
# Load the package (clusterProfiler)
library(clusterProfiler)

# Set the desired organism below
# See all annotations available here: http://bioconductor.org/packages/release/BiocViews.html#___OrgDb
organism = "org.Mm.eg.db"
#BiocManager::install(organism, character.only = TRUE)
library(organism, character.only = TRUE)

# Load the package to do enrichment map (enrichplot)
library(enrichplot)

# Load the package to turn the first letter uppercase with str_to_title (stringr)
library(stringr)
```

```{r Load the package for volcano plot}
# Load the package for volcano plot
library(EnhancedVolcano)
```


# NK/ILC1 gene set enrichment analysis

```{r NK_ILC1 differential expression}
NK_ILC1 <- SetIdent(NK_ILC1, value = "treatment")

# Find the differential expressed genes in NK_ILC1
NK_ILC1_differential <- FindMarkers(NK_ILC1, ident.1 = "Alt.BPC", ident.2 = "Alt", min.cells.group = 10, test.use = "wilcox_limma", only.pos = FALSE, assay = "RNA", slot = "scale.data")

NK_ILC1_differential <- NK_ILC1_differential[order(abs(NK_ILC1_differential$avg_log2FC), decreasing = T), ]

head(NK_ILC1_differential)

# Find the top 5 (positive and negative) differential expression in NK_ILC1
NK_ILC1_differential %>%
  filter(abs(avg_log2FC) > 0.5) %>%
  filter(avg_log2FC > 0) %>%
  top_n(-5, p_val) %>%
  arrange(p_val) -> NK_ILC1_differential_top5pos

head(NK_ILC1_differential_top5pos)

NK_ILC1_differential %>%
  filter(abs(avg_log2FC) > 0.5) %>%
  filter(avg_log2FC < 0) %>%
  top_n(-5, p_val) %>%
  arrange(p_val) -> NK_ILC1_differential_top5neg

head(NK_ILC1_differential_top5neg)
```

```{r NK_ILC1 DE Volcano plot, fig.width = 6, fig.height = 6}
# Plot the top 10 differential genes with volcano plot
NK_ILC1_volcano <- EnhancedVolcano(NK_ILC1_differential,
    lab = rownames(NK_ILC1_differential),
    selectLab = c(rownames(NK_ILC1_differential_top5pos), rownames(NK_ILC1_differential_top5neg)),
    x = 'avg_log2FC',
    y = 'p_val',
    title = 'NK/ILC1 Alt.BPC vs. Alt',
    pCutoff = 10e-7,
    FCcutoff = 0.5,
    pointSize = 3.0,
    labSize = 6.0,
    drawConnectors = TRUE,
    widthConnectors = 0.75,
    colConnectors = 'black') +
  labs(subtitle = NULL)

NK_ILC1_volcano
```

```{r NK_ILC1 GSEA map, fig.height = 16, fig.width = 16}
# Find the top 50% significant differential expression in NK_ILC1
NK_ILC1_differential %>%
  filter(abs(NK_ILC1_differential$avg_log2FC) > 0.5 & p_val < 0.05) %>%
  arrange(p_val) -> NK_ILC1_differential_overTHR

NK_ILC1_differential_overTHR %>%
  top_frac(-0.5, NK_ILC1_differential_overTHR$p_val) -> NK_ILC1_differential_Q2

head(NK_ILC1_differential_Q2)
tail(NK_ILC1_differential_Q2)

# Convert gene label from SYMBOL to ENTREZID
NK_ILC1_gene_id <- bitr(rownames(NK_ILC1_differential_Q2), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db", drop = FALSE)

head(NK_ILC1_gene_id)
tail(NK_ILC1_gene_id)

# Create a gene rank based on the gene expression fold change
NK_ILC1_gene_list <- setNames(NK_ILC1_differential_Q2$avg_log2FC, NK_ILC1_gene_id$ENTREZID)

head(NK_ILC1_gene_list)
tail(NK_ILC1_gene_list)

# Sort the list in decreasing order (required for clusterProfiler)
NK_ILC1_gene_rank = sort(NK_ILC1_gene_list, decreasing = TRUE)

head(NK_ILC1_gene_rank)

# Perform GSE analysis
NK_ILC1_gse <- gseGO(geneList      = NK_ILC1_gene_rank,
                       ont           = "ALL", 
                       keyType       = "ENTREZID", 
                       nPerm         = 10000, 
                       minGSSize     = 10, 
                       maxGSSize     = 1000, 
                       pvalueCutoff  = 0.05, 
                       verbose       = TRUE, 
                       OrgDb         = "org.Mm.eg.db", 
                       pAdjustMethod = "none",
                       by = "fgsea")
# ont setting: one of "BP", "MF", and "CC" subontologies, or "ALL" for all three
# Biological Process (BP):  	biological_process [GO:0008150] <30>
# Cellular Component (CC):  	cellular_component [GO:0005575] <22>
# Molecular Function (MF):  	molecular_function [GO:0003674] <15>


# Select out the top 20 terms based on |enrichmentScore|
NK_ILC1_gse %>%
  filter(abs(enrichmentScore) > 0.5) %>%
  filter(ONTOLOGY == "CC" | ONTOLOGY == "MF") %>%
  top_n(-20, pvalue) %>%
  arrange(desc(leading_edge)) -> NK_ILC1_gse_top20


# Convert gene ID to Symbol
NK_ILC1_gse <- setReadable(NK_ILC1_gse, 'org.Mm.eg.db', 'ENTREZID')

NK_ILC1_gse_top20 <- setReadable(NK_ILC1_gse_top20, 'org.Mm.eg.db', 'ENTREZID')
head(NK_ILC1_gse_top20, 20)

# CategorySize can be either 'pvalue' or 'geneNum'
NK_ILC1_gse_map <- cnetplot(NK_ILC1_gse_top20, categorySize="pvalue", foldChange=NK_ILC1_gene_rank, colorEdge = TRUE, showCategory = 10) +
  labs(title = "NK/ILC1 enrichment map") +
  theme(plot.title = element_text(size=16, face="bold"))

NK_ILC1_gse_map
```


# ILC2 gene set enrichment and analysis

```{r ILC2 differential expression}
ILC2 <- SetIdent(ILC2, value = "treatment")

# Find the differential expressed genes in ILC2
ILC2_differential <- FindMarkers(ILC2, ident.1 = "Alt.BPC", ident.2 = "Alt", min.cells.group = 10, test.use = "wilcox_limma", only.pos = FALSE, assay = "RNA", slot = "scale.data")

ILC2_differential <- ILC2_differential[order(abs(ILC2_differential$avg_log2FC), decreasing = T), ]

head(ILC2_differential)

# Find the top 5 (positive and negative) differential expression in ILC2
ILC2_differential %>%
  filter(abs(avg_log2FC) > 0.5) %>%
  filter(avg_log2FC > 0) %>%
  top_n(-5, p_val) %>%
  arrange(p_val) -> ILC2_differential_top5pos

head(ILC2_differential_top5pos)

ILC2_differential %>%
  filter(abs(avg_log2FC) > 0.5) %>%
  filter(avg_log2FC < 0) %>%
  top_n(-5, p_val) %>%
  arrange(p_val) -> ILC2_differential_top5neg

head(ILC2_differential_top5neg)
```

```{r ILC2 DE Volcano plot, fig.width = 6, fig.height = 6}
# Plot the top 10 differential genes with volcano plot
ILC2_volcano <- EnhancedVolcano(ILC2_differential,
    lab = rownames(ILC2_differential),
    selectLab = c(rownames(ILC2_differential_top5pos), rownames(ILC2_differential_top5neg)),
    x = 'avg_log2FC',
    y = 'p_val',
    title = 'ILC2 Alt.BPC vs. Alt',
    pCutoff = 10e-50,
    FCcutoff = 0.5,
    pointSize = 3.0,
    labSize = 6.0,
    drawConnectors = TRUE,
    widthConnectors = 0.75,
    colConnectors = 'black') +
  labs(subtitle = NULL)

ILC2_volcano
```

```{r ILC2 GSEA map, fig.height = 16, fig.width = 16}
# Find the top 50% significant differential expression in ILC2
ILC2_differential %>%
  filter(abs(ILC2_differential$avg_log2FC) > 0.5 & p_val < 0.05) %>%
  arrange(p_val) -> ILC2_differential_overTHR

ILC2_differential_overTHR %>%
  top_frac(-0.5, ILC2_differential_overTHR$p_val) -> ILC2_differential_Q2

head(ILC2_differential_Q2)
tail(ILC2_differential_Q2)

# Convert gene label from SYMBOL to ENTREZID
ILC2_gene_id <- bitr(rownames(ILC2_differential_Q2), fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db", drop = FALSE)

head(ILC2_gene_id)
tail(ILC2_gene_id)

# Create a gene rank based on the gene expression fold change
ILC2_gene_list <- setNames(ILC2_differential_Q2$avg_log2FC, ILC2_gene_id$ENTREZID)

head(ILC2_gene_list)
tail(ILC2_gene_list)

# Sort the list in decreasing order (required for clusterProfiler)
ILC2_gene_rank = sort(ILC2_gene_list, decreasing = TRUE)

head(ILC2_gene_rank)

# Perform GSE analysis
ILC2_gse <- gseGO(geneList      = ILC2_gene_rank,
                       ont           = "ALL", 
                       keyType       = "ENTREZID", 
                       nPerm         = 10000, 
                       minGSSize     = 10, 
                       maxGSSize     = 1000, 
                       pvalueCutoff  = 0.05, 
                       verbose       = TRUE, 
                       OrgDb         = "org.Mm.eg.db", 
                       pAdjustMethod = "none",
                       by = "fgsea")
# ont setting: one of "BP", "MF", and "CC" subontologies, or "ALL" for all three
# Biological Process (BP):  	biological_process [GO:0008150] <30>
# Cellular Component (CC):  	cellular_component [GO:0005575] <22>
# Molecular Function (MF):  	molecular_function [GO:0003674] <15>


# Select out the top 20 terms based on |enrichmentScore|
ILC2_gse %>%
  filter(abs(enrichmentScore) > 0.5) %>%
  filter(ONTOLOGY == "CC" | ONTOLOGY == "MF") %>%
  top_n(-20, pvalue) %>%
  arrange(desc(leading_edge)) -> ILC2_gse_top20


# Convert gene ID to Symbol
ILC2_gse <- setReadable(ILC2_gse, 'org.Mm.eg.db', 'ENTREZID')

ILC2_gse_top20 <- setReadable(ILC2_gse_top20, 'org.Mm.eg.db', 'ENTREZID')
head(ILC2_gse_top20, 20)

# CategorySize can be either 'pvalue' or 'geneNum'
ILC2_gse_map <- cnetplot(ILC2_gse_top20, categorySize="pvalue", foldChange=ILC2_gene_rank, colorEdge = TRUE, showCategory = 10) +
  labs(title = "ILC2 enrichment map") +
  theme(plot.title = element_text(size=16, face="bold"))

ILC2_gse_map
```


# Data oupput

```{r GSE map for paper, fig.width = 20, fig.height = 20}
# Generate the plot in paper figure form
figure6_1 <- plot_grid(NK_ILC1_volcano, NULL, NK_ILC1_gse_map, labels = c('(A)', '(C)'), label_size = 18, nrow = 1, rel_widths = c(1, 0.1, 2))
figure6_2 <- plot_grid(ILC2_volcano, NULL, ILC2_gse_map, labels = c('(B)', '(D)'), label_size = 18, nrow = 1, rel_widths = c(1, 0.1, 2))

figure6 <- plot_grid(figure6_1, figure6_2,
  nrow = 2,
  ncol = 1,
  rel_heights = c(1, 1)
  )

figure6
```


# Data save

```{r Output the figures}
# Create a folder for the figures
dir.create("./Figures", showWarnings = FALSE)

# Save the figure
ggsave2(plot = figure6, path = "./Figures", "Figure6.tiff", device = "tiff", dpi = 300, bg = "white", width = 20, height = 20, units = "in")
```

```{r Output the CSV files}
# Create a folder for CSV files
dir.create("./CSV", showWarnings = FALSE)

# Export to csv
write.csv(NK_ILC1_differential, file.path("./CSV", "NK_ILC1_differential.csv"))
write.csv(NK_ILC1_gse, file.path("./CSV", "NK_ILC1_gse.csv"))

write.csv(ILC2_differential, file.path("./CSV", "ILC2_differential.csv"))
write.csv(ILC2_gse, file.path("./CSV", "ILC2_gse.csv"))
```


<details>
  <summary>**Session Info**</summary>
```{r}
sessionInfo()
```

