---
title: "CD45+Thy1- cell type identification"
output:
   html_document: 
     theme: united
     df_print: kable
     toc: yes
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
---

```{r setup, include = FALSE}
all_times <- list()  # store the time for each chunk
knitr::knit_hooks$set(time_it = local({
  now <- NULL
  function(before, options) {
    if (before) {
      now <<- Sys.time()
    } else {
      res <- difftime(Sys.time(), now, units = "secs")
      all_times[[options$label]] <<- res
    }
  }
}))
knitr::opts_chunk$set(
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 95),
  message = FALSE,
  warning = FALSE,
  time_it = TRUE
)
```


# Universal packages

```{r Load packages}
library(Seurat)
library(tidyverse)
library(patchwork)
library(cowplot)
```


# Data input

```{r Load SCT processed data}
# Load V5_sen2 subsetted data
Ptprc <- readRDS("../Sensitivity_2_SCT_Thy1_neg_Sub_log_final.rds")

head(x = Ptprc[[]])
```

```{r Set RNA assay as default}
# Show the numbers for the new clusters
table(Ptprc@meta.data$seurat_clusters, split.by = Ptprc@meta.data$treatment)

# Set RNA assay as default
DefaultAssay(Ptprc) <- "RNA"

plot_grid(ncol = 2,
          FeaturePlot(Ptprc, features = c("Ptprc"), slot = "scale.data") + NoAxes() + NoLegend(),
          VlnPlot(Ptprc, features = c("Ptprc"), assay ="RNA", pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5)),
          FeaturePlot(Ptprc, features = c("Thy1"), slot = "scale.data") + NoAxes() + NoLegend(),
          VlnPlot(Ptprc, features = c("Thy1"), assay ="RNA", pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5))
)
```


# Cluster Visualization

```{r Visualize the new clusters, fig.width = 16, fig.height = 20}
# Plot the new clusters
Sub_layout1 <- plot_grid(ncol = 2,
                         DimPlot(Ptprc, label = T, group.by = "seurat_clusters"),
                         DimPlot(Ptprc, group.by = "treatment", label = F) + ggtitle(NULL)
                         )

Sub_layout2 <- plot_grid(ncol = 4,
                         FeaturePlot(Ptprc, features = c("Itgam")) + NoAxes() + NoLegend(),
                         VlnPlot(Ptprc, features = c("Itgam"), pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5)),
                         FeaturePlot(Ptprc, features = c("Itgax")) + NoAxes() + NoLegend(),
                         VlnPlot(Ptprc, features = c("Itgax"), pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5)),
                         FeaturePlot(Ptprc, features = c("H2-Aa")) + NoAxes() + NoLegend(),
                         VlnPlot(Ptprc, features = c("H2-Aa"), pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5)),
                         FeaturePlot(Ptprc, features = c("Cd86")) + NoAxes() + NoLegend(),
                         VlnPlot(Ptprc, features = c("Cd86"), pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5)),
                         FeaturePlot(Ptprc, features = c("Cd79a")) + NoAxes() + NoLegend(),
                         VlnPlot(Ptprc, features = c("Cd79a"), pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5)),
                         FeaturePlot(Ptprc, features = c("Mpo")) + NoAxes() + NoLegend(),
                         VlnPlot(Ptprc, features = c("Mpo"), pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5)),
                         FeaturePlot(Ptprc, features = c("Fcer1a")) + NoAxes() + NoLegend(),
                         VlnPlot(Ptprc, features = c("Fcer1a"), pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5)),
                         FeaturePlot(Ptprc, features = c("Cma1")) + NoAxes() + NoLegend(),
                         VlnPlot(Ptprc, features = c("Cma1"), pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5)),
                         FeaturePlot(Ptprc, features = c("Adgre1")) + NoAxes() + NoLegend(),
                         VlnPlot(Ptprc, features = c("Adgre1"), pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5)),
                         FeaturePlot(Ptprc, features = c("Siglecf")) + NoAxes() + NoLegend(),
                         VlnPlot(Ptprc, features = c("Siglecf"), pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5))
                         )

(Sub_layout1)/
  (Sub_layout2) +
  plot_layout(heights = c(1, 4))

Sub_layout3 <- plot_grid(ncol = 4,
                         FeaturePlot(Ptprc, features = c("Csf1r"), slot = "scale.data") + NoAxes() + NoLegend(),
                         VlnPlot(Ptprc, features = c("Csf1r"), assay ="RNA", pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5)),
                         FeaturePlot(Ptprc, features = c("Spn"), slot = "scale.data") + NoAxes() + NoLegend(),
                         VlnPlot(Ptprc, features = c("Spn"), assay ="RNA", pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5)),
                         FeaturePlot(Ptprc, features = c("Klf2"), slot = "scale.data") + NoAxes() + NoLegend(),
                         VlnPlot(Ptprc, features = c("Klf2"), assay ="RNA", pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5)),
                         FeaturePlot(Ptprc, features = c("Cd14"), slot = "scale.data") + NoAxes() + NoLegend(),
                         VlnPlot(Ptprc, features = c("Cd14"), assay ="RNA", pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5)),
                         FeaturePlot(Ptprc, features = c("Irf8"), slot = "scale.data") + NoAxes() + NoLegend(),
                         VlnPlot(Ptprc, features = c("Irf8"), assay ="RNA", pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5)),
                         FeaturePlot(Ptprc, features = c("Itgae"), slot = "scale.data") + NoAxes() + NoLegend(),
                         VlnPlot(Ptprc, features = c("Itgae"), assay ="RNA", pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5)),
                         FeaturePlot(Ptprc, features = c("Clec9a"), slot = "scale.data") + NoAxes() + NoLegend(),
                         VlnPlot(Ptprc, features = c("Clec9a"), assay ="RNA", pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5)),
                         FeaturePlot(Ptprc, features = c("Clec10a"), slot = "scale.data") + NoAxes() + NoLegend(),
                         VlnPlot(Ptprc, features = c("Clec10a"), assay ="RNA", pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5)),
                         FeaturePlot(Ptprc, features = c("Irf4"), slot = "scale.data") + NoAxes() + NoLegend(),
                         VlnPlot(Ptprc, features = c("Irf4"), assay ="RNA", pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5)),
                         FeaturePlot(Ptprc, features = c("Ccr7"), slot = "scale.data") + NoAxes() + NoLegend(),
                         VlnPlot(Ptprc, features = c("Ccr7"), assay ="RNA", pt.size = 0.1) + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0, hjust = 0.5))
                         )

(Sub_layout1)/
  Sub_layout3 +
  plot_layout(heights = c(1, 4))
```


# Cell type annotation

```{r Add cell type annotation}
# B cell: Cd79a+ (cluster 5)

# Granulocyte gene markers:
# https://www.biocompare.com/Editorial-Articles/594281-A-Guide-to-Granulocyte-Markers/
# Mast cell: Fcer1a+ Cma1+ (cluster 6)
# Neutrophil: Mpo+ (cluster 7)

# Macrophage/Monocyte gene markers:
# https://www.biocompare.com/Editorial-Articles/566347-A-Guide-to-Macrophage-Markers/
# https://www.biocompare.com/Editorial-Articles/567890-A-Guide-to-Monocyte-Markers/
# Alveolar macrophage (Alveolar MΦ): Itgax+ Adgre1+ Siglecf+ Csf1r+ (cluster 1)
# Monocyte (Mo): Csf1r+ Spn+ Klf2+ Cd14+ (cluster 3)

# DC gene markers:
# https://www.biocompare.com/Editorial-Articles/572982-Dendritic-Cell-Markers/
# cDC2: Igtam+ Igtax+ MHCII+ Cd86+ Clec10a+ Irf4+ (cluster 0)
# cDC1: Igtax+ MHCII+ Cd86+ Irf8+ Itgae+ Clec9a+ (cluster 2)
# Mature DC: Igtax+ MHCII+ Cd86+ Ccr7+ (cluster 4)

# Label the cell type annotation to all the clusters
new.Ptprc.ids <- c("cDC2", "Alveolar MΦ", "cDC1", "Mo", "Mature DC", "B", "Mast", "Neu")
names(new.Ptprc.ids) <- levels(Ptprc)
Ptprc_labeled <- RenameIdents(Ptprc, new.Ptprc.ids)
Ptprc_labeled <- AddMetaData(Ptprc_labeled, metadata = Ptprc_labeled@active.ident, col.name = 'cell_type')

DimPlot(Ptprc_labeled, label = T, repel = T, group.by = "cell_type") +
  labs(title = "Ptprc Subsets") + 
  theme(legend.text = element_text(size = 14), plot.title = element_text(size = 16))

DimPlot(Ptprc_labeled, group.by = "cell_type", split.by = "treatment", label = F) +
  labs(title = "Ptprc Subsets", subtitle = "Split by treatments") + 
  theme(legend.text = element_text(size = 14), plot.title = element_text(size = 16), axis.title = element_text(size = 12))

# Show the numbers for the Ptprc cell across the conditions
table(Ptprc_labeled@active.ident, split.by = Ptprc_labeled@meta.data$treatment)
```

```{r Ptprc differential markers, fig.height = 4, fig.width = 10}
# Differential gene sets
B <- c("Cd79a", "Cd79b", "Igkc")
Neu <- c("Mpo", "Elane")
mast <- c("Fcer1a", "Cma1")
Mo <- c("Ly6g6c", "Csf1r", "Cd14")
AM <- c("Adgre1", "Siglecf", "Mrc1")
MHC2 <- c("H2-Aa", "H2-Ab1", "H2-Ea", "H2-Eb1", "H2-Eb2", "H2-Pa", "H2-Pb", "H2-DMa", "H2-DMb1", "H2-DMb2")
mature <- c("Ccr7", "Cd80", "Cd86")
cDC1 <- c("Irf8", "Clec9a", "Itgae")
cDC2 <- c("Irf2", "Irf4", "Clec10a")

functional_gene <- list("B" = B, "Neu" = Neu, "Mast" = mast, "Mo" = Mo, "AM" = AM, "MHC II" = MHC2, "Mature" = mature, "cDC1" = cDC1, "cDC2" = cDC2)

Ptprc_differential <- DotPlot(Ptprc_labeled, features = functional_gene, group.by = "cell_type", assay = "RNA", cols = "RdBu") + theme(axis.title = element_blank(), legend.title = element_text(size = 8, face ="bold"), legend.text = element_text(size = 8), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  ggtitle("Differential markers for CD45+Thy1- subsets")

Ptprc_differential
```

```{r Marker genes for the clusters, fig.width = 12, fig.height = 12}
# Compute differential expression
marker_genes <- FindAllMarkers(Ptprc_labeled, log2FC.threshold = 0.2, test.use = "wilcox", min.pct = 0.1, min.diff.pct = 0.2, only.pos = TRUE, max.cells.per.ident = 50, assay = "RNA")

# Get genes that are positivelly expressed in a cell type and possibly not expressed in the others
# Select the top 5 to visualize as plots
marker_genes %>%
    group_by(cluster) %>%
    top_n(-5, p_val_adj) -> top5

# Plot Heatmap
markers_heatmap <- DoHeatmap(Ptprc_labeled, features = as.character(unique(top5$gene)), group.by = "cell_type", assay = "RNA", slot = 'scale.data', group.bar.height = 0.01, label = F)

markers_heatmap
```


# Cell distribution among the conditions

```{r Cell type distribution}
# Set the themes
xtheme <- theme_bw() +
  theme(plot.title = element_text(face = "bold",hjust = 0.5, size= 10),
        axis.text.y = element_text(face = "bold",angle = 0, size = 10, hjust=1),
        axis.title.y = element_text(face = "bold", size = rel(1.2)),
        axis.text.x = element_text(face = "bold",angle = 0, size = 10),
        axis.title.x = element_text(face = "bold", size = rel(1.4)),
        axis.ticks.x = element_blank(), strip.text = element_text(size=10))

# Reveal the distributional change in Ptprc cells among the conditions
Ptprc.distribution <- data.frame(Ptprc_labeled@active.ident, Ptprc_labeled@meta.data$treatment) 
colnames(Ptprc.distribution) <- c("Cell_Type", "Treatment")
Ptprc.distribution <- Ptprc.distribution %>% group_by(Cell_Type, Treatment) %>% 
  summarise(Nb = n()) %>%
  mutate(C = sum(Nb)) %>%
  mutate(Percent = Nb/C*100) 

ggplot(Ptprc.distribution, aes(fill = Treatment, y = Percent, x = Cell_Type)) + 
  geom_bar(position="fill", stat="identity") + xlab("") + ylab("Proportion") + xtheme + 
  theme(legend.position='right', axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
  theme(legend.title = element_text(size = 14, face = "bold"), legend.text = element_text(size = 14)) +
  ggtitle("Ptprc cell distribution across the treatments") +
  theme(plot.title = element_text(size = 16))
```


# Paper figure layout

```{r Paper figure S4 layout, fig.width = 12, fig.height = 14}
# Generate the plot in paper figure form
figureS4 <- plot_grid(Ptprc_differential, markers_heatmap,
  labels = c('(A)', '(B)'), label_size = 18,
  nrow = 2,
  ncol = 1,
  rel_heights = c(1, 3)
)

figureS4
```


# Data save

```{r Output the figure}
# Create a folder for the figures
dir.create("./Figures", showWarnings = FALSE)

# Save the figures
ggsave2(plot = figureS4, path = "./Figures", "FigureS4.tiff", device = "tiff", dpi = 300, bg = "white", width = 12, height = 14, units = "in")
```

```{r Save RDS}
saveRDS(Ptprc_labeled, file = "CD45_Thy1_neg_labeled_paper_ver.rds")
```


<details>
  <summary>**Session Info**</summary>
```{r sessionInfo}
sessionInfo()
```

